version: '3.5'

services:
  # The php Applications
  app:
    container_name: laravel_app
    build:
      context: ./
      args:
        - WITH_XDEBUG=true
      dockerfile: app.docker
    working_dir: /var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.3"
      PHP_IDE_CONFIG: "serverName=laravel-app.local"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa_host
      - ./:/var/www:cached
    ports:
      - 8000:80
    expose:
      - 8000
    networks:
      backend:
        aliases:
          - laravel-app
  # The Web Server
  web:
    container_name: laravel_web
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa_host
      - ./:/var/www:cached
    links:
      - db
    ports:
      - 8080:80
    expose:
      - 8080
    networks:
      backend:
        aliases:
          - laravel-app

  # The DB Server
  db:
    container_name: laravel_db
    image: mysql:8.0.17
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./conf/mysql/mysql_extra.cnf:/etc/mysql/conf.d/mysql_extra1.cnf:ro"
      - "./conf/mysql/init:/docker-entrypoint-initdb.d:ro"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      backend:
        aliases:
          - db

      # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
networks:
  backend:
    name: backend-network
